"""Base protocol and request data model for AI Composition Providers."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Protocol


@dataclass
class CompositionRequest:
    """High-level user request for AI music composition."""
    style: str = "action"
    mood: Optional[List[str]] = None
    duration_seconds: int = 24
    bpm: Optional[int] = None
    key: Optional[str] = None
    mode: Optional[str] = None
    channels: int = 4
    use_16bit_bass: bool = False
    structure: Optional[str] = None
    notes: Optional[str] = None
    seed: Optional[int] = None


class AICompositionProvider(Protocol):
    """Protocol for AI music composition backends (OpenAI, Local LLM, Mock)."""

    @property
    def provider_name(self) -> str:
        """Name of the provider service."""
        ...

    def generate_composition(
        self,
        request: CompositionRequest,
        feedback: Optional[str] = None,
        previous_composition: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Generate raw AI composition dictionary from prompt request.
        
        Parameters
        ----------
        request : CompositionRequest
            The musical prompt parameters.
        feedback : Optional[str]
            Structured feedback from previous validation failures (used during retry).
        previous_composition : Optional[Dict[str, Any]]
            The raw JSON dictionary of the previous invalid attempt to repair.
            
        Returns
        -------
        Dict[str, Any]
            Raw JSON dictionary generated by the model.
        """
        ...

